(eagerpy:convert)=
# EagerPy 和 Native 张量之间的变换

原生张量可以是 PyTorch GPU 或 CPU 张量、TensorFlow 张量、JAX 数组或 NumPy 数组。

```{rubric} 原生的 PyTorch 张量
```

In [1]:
import torch
x = torch.tensor([1., 2., 3., 4., 5., 6.])
x

tensor([1., 2., 3., 4., 5., 6.])

```{rubric} 原生的 TensorFlow 张量
```

In [1]:
import tensorflow as tf
x = tf.constant([1., 2., 3., 4., 5., 6.])
x

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

```{rubric} 原生的 JAX 数组
```

In [3]:
import jax.numpy as np
x = np.array([1., 2., 3., 4., 5., 6.])
x

DeviceArray([1., 2., 3., 4., 5., 6.], dtype=float32)

```{rubric} 原生的 NumPy 数组
```

In [4]:
import numpy as np
x = np.array([1., 2., 3., 4., 5., 6.])
x

array([1., 2., 3., 4., 5., 6.])

无论你有哪个原生张量，它总是可以通过 `ep.astensor` 转换成相应的 `EagerPy` 张量。这将自动使用正确的 `EagerPy` 张量类包装原生张量。原始的原生张量总是可以使用 `.raw` 属性访问。

In [1]:
# x 应该是原生张量(参见上面)
# 例如:
import torch
x = torch.tensor([1., 2., 3., 4., 5., 6.])

# 任何原生张量都可以很容易地转化为 EagerPy 张量
import eagerpy as ep
x = ep.astensor(x)

# 可以执行任何 EagerPy 运算
x = x.square()

# 然后把 EagerPy 张量转换回原生张量
x = x.raw
# x 现在将再次是原生张量(例如 PyTorch 张量)
x

tensor([ 1.,  4.,  9., 16., 25., 36.])

特别是在函数中，将所有输入转换为 EagerPy 张量是很常见的。这可以通过单独调用 `ep.astensor` 来完成，但是用 `ep.astensors` 可以写得更紧凑。

In [2]:
# x，y 应该是原生张量(参见上面)
# 例如:
import torch
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])

import eagerpy as ep
x, y = ep.astensors(x, y)  # 适用于任何数量的输入